resilience4j.retry.instances.info.maxAttempts=5
resilience4j.retry.instances.status.maxAttempts=5

resilience4j.circuitbreaker.instances.cpuPredict.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cpuPredict.minimumNumberOfCalls=6
resilience4j.circuitbreaker.instances.cpuPredict.waitDurationInOpenState=3s
resilience4j.circuitbreaker.instances.cpuPredict.failureRateThreshold=50

server.port=8080
