# JWT verification - start (redhattraining issuer; complete lab to add groups/roles)
jwt.issuer=https://example.com/redhattraining
jwt.public-key-location=file:${user.home}/DO378/secure-jwt/publicKey.pem
jwt.private-key-location=file:${user.home}/DO378/secure-jwt/privateKey.pem

spring.security.oauth2.resourceserver.jwt.public-key-location=${jwt.public-key-location}
