spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testing
    username: developer
    password: developer
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  kafka:
    bootstrap-servers: localhost:9092
