spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-detector
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.bcp.training.event

server:
  port: 8081
