server.port=8080
expense.service.url=${EXPENSE_SVC:http://localhost:8081}

# Health probes para Kubernetes/Azure (liveness + readiness)
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
