server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:tcp://schedules-db.conference.svc.cluster.local/~/schedules
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
