server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tc-test
    username: tc-user
    password: tc-pass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
