server.port=8080
spring.profiles.active=dev

# Nivel por defecto: INFO
logging.level.root=INFO

# Habilita DEBUG solo para el paquete del ejercicio (para que se vean logs relevantes)
logging.level.com.bcp.training.expense=DEBUG

# Archivo usado por el laboratorio (perfil dev)
logging.file.name=${HOME}/DO378/monitor-logging/dev.logs
logging.pattern.file=%d %-5p [%F] %m%n

