spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testing
    username: developer
    password: developer
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: joedayz-bank
      account-type-group-id: joedayz-bank-account-type-v2
      auto-offset-reset: earliest

#logging:
#  level:
#    org.springframework.kafka: DEBUG