# JWT verification (resource server) - static public key
jwt.issuer=https://example.com/bcptraining
jwt.public-key-location=file:${user.home}/DO378/secure-jwt/publicKey.pem
jwt.private-key-location=file:${user.home}/DO378/secure-jwt/privateKey.pem

spring.security.oauth2.resourceserver.jwt.public-key-location=${jwt.public-key-location}
